[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "node build/bin/server.js"
preDeployCommand = "node build/ace.js migration:run --force"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
