/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  AdminStats: () => import('#controllers/admin_stats_controller'),
  AdminUsers: () => import('#controllers/admin_users_controller'),
  Fleet: () => import('#controllers/fleet_controller'),
  InternalCorporateOrders: () => import('#controllers/internal_corporate_orders_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  PublicTracking: () => import('#controllers/public_tracking_controller'),
  Sadev: () => import('#controllers/sadev_controller'),
  TrackingOrders: () => import('#controllers/tracking_orders_controller'),
}
