/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DriverShiftSchema extends BaseModel {
  static $columns = ['createdAt', 'endedAt', 'id', 'startedAt', 'updatedAt', 'userId', 'vehicleId'] as const
  $columns = DriverShiftSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare endedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare startedAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare vehicleId: number
}

export class SyncJobLeaseSchema extends BaseModel {
  static $columns = ['expiresAt', 'holder', 'jobName'] as const
  $columns = SyncJobLeaseSchema.$columns
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare holder: string
  @column({ isPrimary: true })
  declare jobName: string
}

export class TrackingOrderItemSchema extends BaseModel {
  static $columns = ['cantidad', 'codigoItem', 'codigoUnidadVenta', 'createdAt', 'descripcionItem', 'id', 'lineIndex', 'precio', 'trackingOrderId', 'updatedAt'] as const
  $columns = TrackingOrderItemSchema.$columns
  @column()
  declare cantidad: string
  @column()
  declare codigoItem: string | null
  @column()
  declare codigoUnidadVenta: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcionItem: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare lineIndex: number
  @column()
  declare precio: string
  @column()
  declare trackingOrderId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TrackingOrderLocationSchema extends BaseModel {
  static $columns = ['accuracyMeters', 'createdAt', 'id', 'latitude', 'longitude', 'orderDocument', 'provider', 'recordedAt', 'speedMps', 'trackingOrderId', 'updatedAt', 'vehicleId'] as const
  $columns = TrackingOrderLocationSchema.$columns
  @column()
  declare accuracyMeters: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare latitude: string
  @column()
  declare longitude: string
  @column()
  declare orderDocument: string
  @column()
  declare provider: string | null
  @column.dateTime()
  declare recordedAt: DateTime
  @column()
  declare speedMps: string | null
  @column()
  declare trackingOrderId: bigint | number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vehicleId: number | null
}

export class TrackingOrderObservationSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'id', 'trackingOrderId', 'updatedAt', 'userId'] as const
  $columns = TrackingOrderObservationSchema.$columns
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare trackingOrderId: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class TrackingOrderSchema extends BaseModel {
  static $columns = ['adminFeedbackAt', 'adminReaction', 'claimedByUserId', 'codigoUbicacion', 'codigoVendedor', 'createdAt', 'descripcionPedido', 'destinationAddress', 'destinationLat', 'destinationLng', 'destinationMapsLink', 'destinationSource', 'estadoCodigo', 'id', 'isSync', 'montoTotal', 'numeroDocumento', 'originAddress', 'originDepotCode', 'originLat', 'originLng', 'originName', 'sadevCompletedPushedAt', 'status', 'syncedAt', 'tipoFactura', 'transportStartedAt', 'updatedAt', 'vehicleId'] as const
  $columns = TrackingOrderSchema.$columns
  @column.dateTime()
  declare adminFeedbackAt: DateTime | null
  @column()
  declare adminReaction: string | null
  @column()
  declare claimedByUserId: number | null
  @column()
  declare codigoUbicacion: string | null
  @column()
  declare codigoVendedor: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcionPedido: string | null
  @column()
  declare destinationAddress: string | null
  @column()
  declare destinationLat: string | null
  @column()
  declare destinationLng: string | null
  @column()
  declare destinationMapsLink: string | null
  @column()
  declare destinationSource: string | null
  @column()
  declare estadoCodigo: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare isSync: boolean
  @column()
  declare montoTotal: string
  @column()
  declare numeroDocumento: string
  @column()
  declare originAddress: string | null
  @column()
  declare originDepotCode: string | null
  @column()
  declare originLat: string | null
  @column()
  declare originLng: string | null
  @column()
  declare originName: string | null
  @column.dateTime()
  declare sadevCompletedPushedAt: DateTime | null
  @column()
  declare status: number
  @column.dateTime()
  declare syncedAt: DateTime | null
  @column()
  declare tipoFactura: string | null
  @column.dateTime()
  declare transportStartedAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vehicleId: number | null
}

export class TrackingPublicEventSchema extends BaseModel {
  static $columns = ['attemptCount', 'createdAt', 'direction', 'eventId', 'eventType', 'id', 'lastError', 'nextRetryAt', 'orderDocument', 'payload', 'sentAt', 'status', 'updatedAt'] as const
  $columns = TrackingPublicEventSchema.$columns
  @column()
  declare attemptCount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare direction: string
  @column()
  declare eventId: string
  @column()
  declare eventType: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare lastError: string | null
  @column.dateTime()
  declare nextRetryAt: DateTime | null
  @column()
  declare orderDocument: string
  @column()
  declare payload: string
  @column.dateTime()
  declare sentAt: DateTime | null
  @column()
  declare status: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['approvalStatus', 'approvedAt', 'approvedBy', 'avatarUrl', 'createdAt', 'email', 'fullName', 'id', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare approvalStatus: string
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column()
  declare approvedBy: number | null
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VehicleExpenseSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'currency', 'expenseDate', 'expenseType', 'id', 'notes', 'tripCount', 'updatedAt', 'vehicleId'] as const
  $columns = VehicleExpenseSchema.$columns
  @column()
  declare amount: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column.dateTime()
  declare expenseDate: DateTime
  @column()
  declare expenseType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notes: string | null
  @column()
  declare tripCount: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vehicleId: number
}

export class VehicleSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'id', 'imageUrl', 'name', 'odometerKm', 'operationalStatus', 'updatedAt'] as const
  $columns = VehicleSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageUrl: string | null
  @column()
  declare name: string
  @column()
  declare odometerKm: string
  @column()
  declare operationalStatus: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
